<?php

namespace AppBundle\Repository;

/**
 * ContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactRepository extends \Doctrine\ORM\EntityRepository
{
    public function findWithSociete($id)
    {
        $dql = "SELECT c, s "
             . "FROM AppBundle\Entity\Contact c "
             . "LEFT JOIN c.societe s "
             . "WHERE c.id = :id";
        
        $query = $this->getEntityManager()->createQuery($dql);
        
        $query->setParameter('id', $id);
        
        return $query->getSingleResult();
    }
}
